# Generated by Django 5.2.13 on 2026-04-17 13:45

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='菜单标题')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='路由名称')),
                ('path', models.CharField(blank=True, default='', max_length=200, verbose_name='路由路径')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('component', models.CharField(blank=True, default='', help_text='前端 src/views/ 下的路径，如 article/list', max_length=200, verbose_name='组件路径')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_hidden', models.BooleanField(default=False, help_text='隐藏菜单仍可访问，只是不显示在侧边栏', verbose_name='是否隐藏')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'sys_menu',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组织名称')),
                ('code', models.CharField(help_text='唯一标识，如 DEPT_IT', max_length=50, unique=True, verbose_name='组织编码')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.organization', verbose_name='上级组织')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'db_table': 'sys_organization',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('code', models.CharField(help_text='唯一标识，如 user:user:list，用于后端接口鉴权', max_length=100, unique=True, verbose_name='权限码')),
                ('url_pattern', models.CharField(blank=True, default='', help_text='URL 正则模式，如 ^/api/user/，用于 URL 模式鉴权', max_length=200, verbose_name='URL匹配')),
                ('ptype', models.CharField(choices=[('menu', '菜单权限'), ('button', '按钮权限'), ('field', '字段权限'), ('api', 'API权限')], default='api', max_length=20, verbose_name='权限类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.menu', verbose_name='关联菜单')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'sys_permission',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('code', models.CharField(help_text='唯一标识，如 role_admin', max_length=50, unique=True, verbose_name='角色编码')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('data_scope', models.CharField(choices=[('ALL', '全部数据'), ('org', '本组织及下级'), ('dept', '本部门'), ('SELF', '仅本人数据')], default='SELF', max_length=20, verbose_name='数据范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='rbac.menu', verbose_name='关联菜单（用于侧边栏）')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='rbac.permission', verbose_name='关联权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'sys_role',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
