# Generated by Django 5.2.15 on 2026-06-09 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_add_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_unique',
            field=models.BooleanField(default=False, help_text='开启后全局只能有一个用户持有该角色（如 BOSS）', verbose_name='唯一角色'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('permission_code', models.CharField(max_length=100, verbose_name='权限编码')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
                'db_table': 'rbac_role_permissions',
                'unique_together': {('role', 'permission_code')},
            },
        ),
    ]
